ALTER TABLE "accounts" ADD COLUMN "name_translations" jsonb;
ALTER TABLE "budgets" ADD COLUMN "name_translations" jsonb;
ALTER TABLE "categories" ADD COLUMN "name_translations" jsonb;
ALTER TABLE "goals" ADD COLUMN "name_translations" jsonb;
ALTER TABLE "goals" ADD COLUMN "notes_translations" jsonb;
ALTER TABLE "rules" ADD COLUMN "name_translations" jsonb;
ALTER TABLE "trading_agents" ADD COLUMN "name_translations" jsonb;
ALTER TABLE "transactions" ADD COLUMN "description_translations" jsonb;
ALTER TABLE "transactions" ADD COLUMN "notes_translations" jsonb;